# Stage 1: Build the application
FROM registry.access.redhat.com/ubi8/dotnet-80 AS builder

USER root

WORKDIR /app

# Copy the project file and restore dependencies
COPY ../my-app.Service/*.csproj ./
RUN dotnet restore

# Copy the rest of the source code
COPY ../my-app.Service/ ./

# Build the application
RUN dotnet publish -c Release -o out

# Stage 2: Create the runtime image
FROM registry.access.redhat.com/ubi8/dotnet-80-runtime AS runner

WORKDIR /app

# Copy the published output from the builder stage
COPY --from=builder --chown=1001:0 /app/out .

# Ensure the application runs as non-root
USER 1001

ENV PORT 8080

EXPOSE 8080

# Start the application
CMD ["dotnet", "my-app.Service.dll"]
